[2023-09-21T12:17:48.849+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: master_dag.trigger_cleaning scheduled__2023-09-21T00:00:00+00:00 [queued]>
[2023-09-21T12:17:48.856+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: master_dag.trigger_cleaning scheduled__2023-09-21T00:00:00+00:00 [queued]>
[2023-09-21T12:17:48.858+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-21T12:17:48.870+0000] {taskinstance.py:1380} INFO - Executing <Task(TriggerDagRunOperator): trigger_cleaning> on 2023-09-21 00:00:00+00:00
[2023-09-21T12:17:48.875+0000] {standard_task_runner.py:57} INFO - Started process 10489 to run task
[2023-09-21T12:17:48.880+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'master_dag', 'trigger_cleaning', 'scheduled__2023-09-21T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/master_dag.py', '--cfg-path', '/tmp/tmpejc9cwbq']
[2023-09-21T12:17:48.884+0000] {standard_task_runner.py:85} INFO - Job 41: Subtask trigger_cleaning
[2023-09-21T12:17:48.943+0000] {task_command.py:415} INFO - Running <TaskInstance: master_dag.trigger_cleaning scheduled__2023-09-21T00:00:00+00:00 [running]> on host c14470e00ccc
[2023-09-21T12:17:49.024+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='master_dag' AIRFLOW_CTX_TASK_ID='trigger_cleaning' AIRFLOW_CTX_EXECUTION_DATE='2023-09-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-21T00:00:00+00:00'
[2023-09-21T12:17:49.147+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=master_dag, task_id=trigger_cleaning, execution_date=20230921T000000, start_date=20230921T121748, end_date=20230921T121749
[2023-09-21T12:17:49.179+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-21T12:17:49.219+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-21T13:42:27.522+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: master_dag.trigger_cleaning scheduled__2023-09-21T00:00:00+00:00 [queued]>
[2023-09-21T13:42:27.529+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: master_dag.trigger_cleaning scheduled__2023-09-21T00:00:00+00:00 [queued]>
[2023-09-21T13:42:27.530+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-21T13:42:27.541+0000] {taskinstance.py:1380} INFO - Executing <Task(TriggerDagRunOperator): trigger_cleaning> on 2023-09-21 00:00:00+00:00
[2023-09-21T13:42:27.547+0000] {standard_task_runner.py:57} INFO - Started process 15526 to run task
[2023-09-21T13:42:27.552+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'master_dag', 'trigger_cleaning', 'scheduled__2023-09-21T00:00:00+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/master_dag.py', '--cfg-path', '/tmp/tmpghnsvdf_']
[2023-09-21T13:42:27.556+0000] {standard_task_runner.py:85} INFO - Job 153: Subtask trigger_cleaning
[2023-09-21T13:42:27.615+0000] {task_command.py:415} INFO - Running <TaskInstance: master_dag.trigger_cleaning scheduled__2023-09-21T00:00:00+00:00 [running]> on host c14470e00ccc
[2023-09-21T13:42:27.696+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='master_dag' AIRFLOW_CTX_TASK_ID='trigger_cleaning' AIRFLOW_CTX_EXECUTION_DATE='2023-09-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-21T00:00:00+00:00'
[2023-09-21T13:42:27.719+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/trigger_dagrun.py", line 163, in execute
    dag_run = trigger_dag(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/api/common/trigger_dag.py", line 119, in trigger_dag
    raise DagNotFound(f"Dag id {dag_id} not found in DagModel")
airflow.exceptions.DagNotFound: Dag id cleaning_dag not found in DagModel
[2023-09-21T13:42:27.724+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=master_dag, task_id=trigger_cleaning, execution_date=20230921T000000, start_date=20230921T134227, end_date=20230921T134227
[2023-09-21T13:42:27.734+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 153 for task trigger_cleaning (Dag id cleaning_dag not found in DagModel; 15526)
[2023-09-21T13:42:27.764+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-21T13:42:27.784+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
