[2023-09-18T12:50:47.546+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraper_dag_v1.get_ids manual__2023-09-18T12:50:43.998895+00:00 [queued]>
[2023-09-18T12:50:47.555+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraper_dag_v1.get_ids manual__2023-09-18T12:50:43.998895+00:00 [queued]>
[2023-09-18T12:50:47.556+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-18T12:50:47.568+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): get_ids> on 2023-09-18 12:50:43.998895+00:00
[2023-09-18T12:50:47.576+0000] {standard_task_runner.py:57} INFO - Started process 2946 to run task
[2023-09-18T12:50:47.580+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scraper_dag_v1', 'get_ids', 'manual__2023-09-18T12:50:43.998895+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/scraper_dag.py', '--cfg-path', '/tmp/tmpb4csjl76']
[2023-09-18T12:50:47.585+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask get_ids
[2023-09-18T12:50:47.642+0000] {task_command.py:415} INFO - Running <TaskInstance: scraper_dag_v1.get_ids manual__2023-09-18T12:50:43.998895+00:00 [running]> on host ae4a9cdd5e86
[2023-09-18T12:50:47.746+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='felicien' AIRFLOW_CTX_DAG_ID='scraper_dag_v1' AIRFLOW_CTX_TASK_ID='get_ids' AIRFLOW_CTX_EXECUTION_DATE='2023-09-18T12:50:43.998895+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-18T12:50:43.998895+00:00'
[2023-09-18T12:50:47.748+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: id_scraper() missing 1 required positional argument: 'pages'
[2023-09-18T12:50:47.761+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=scraper_dag_v1, task_id=get_ids, execution_date=20230918T125043, start_date=20230918T125047, end_date=20230918T125047
[2023-09-18T12:50:47.772+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task get_ids (id_scraper() missing 1 required positional argument: 'pages'; 2946)
[2023-09-18T12:50:47.793+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-18T12:50:47.813+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
